object Libs {
    const val ACTIVITY_COMPOSE = "androidx.activity:activity-compose"
    const val COIL = "io.coil-kt:coil-compose"
    const val COMPOSE_UI = "androidx.compose.ui:ui"
    const val COMPOSE_MATERIAL = "androidx.compose.material:material"
    const val COMPOSE_UI_TOOLING_PREVIEW = "androidx.compose.ui:ui-tooling-preview"
    const val COMPOSE_UI_TOOLING = "androidx.compose.ui:ui-tooling"
    const val COMPOSE_UI_TEST_JUNIT = "androidx.compose.ui:ui-test-junit4"
    const val COMPOSE_UI_TEST_MANIFEST = "androidx.compose.ui:ui-test-manifest"
    const val CONSTRAINT_LAYOUT_COMPOSE = "androidx.constraintlayout:constraintlayout-compose"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core"
    const val EXT_JUNIT = "androidx.test.ext:junit"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val JUNIT = "junit:junit"
    const val LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val LIFECYCLE_VIEW_MODEL_COMPOSE = "androidx.lifecycle:lifecycle-viewmodel-compose"
    const val NAVIGATION_COMPOSE = "androidx.navigation:navigation-compose"
    const val OKHTTP_LOGGING_INTERCEPTER = "com.squareup.okhttp3:logging-interceptor"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_GSON_CONVERTER = "com.squareup.retrofit2:converter-gson"
    const val TIMBER = "com.jakewharton.timber:timber"
}